[package]
name = "client"
version = "0.1.0"
authors = ["Kevin Leimkuhler <kevin@kleimkuhler.com>"]

[dependencies]
bincode = "1.0.1"
bytes = { version = "0.4.11", features = ["serde"] }
futures = "0.1.25"
serde = "1.0.80"
serde_derive = "1.0.80"
tokio = "0.1.13"
